apiVersion: v1
kind: PersistentVolume
metadata:
  name: test-pv
spec:
  accessModes:
  - ReadWriteOnce
  capacity:
    storage: 20Gi
  csi:
    driver: ebs.csi.aws.com
    fsType: ext4
    volumeHandle: vol-01fca4d5c780ac73e
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: static-volume
spec:
  accessModes:
    - ReadWriteOnce
  storageClassName: ebs-sc
  resources:
    requests:
      storage: 4Gi
---
apiVersion: v1
kind: Pod
metadata:
  name: staticvolume
spec:
  containers:
  - name: app
    image: nginx
    volumeMounts:
    - name: static-volume
      mountPath: /data
  volumes:
  - name: static-volume
    persistentVolumeClaim:
      claimName: ebs-claim      

    
  







#Static provissioning
#we need to create the volume in the aws in required avalabality zone
#install the drivers (aws-ebs-csi-driver) useing follwing command
# { kubectl apply -k "github.com/kubernetes-sigs/aws-ebs-csi-driver/deploy/kubernetes/overlays/stable/?ref=release-1.37" }

