apiVersion: v1
kind: PersistentVolume
metadata:
  name: test-pv
spec:
  accessModes:
  - ReadWriteOnce
  capacity:
    storage: 20Gi
  csi:
    driver: ebs.csi.aws.com
    fsType: ext4
    volumeHandle: vol-01fca4d5c780ac73e
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: static-volume
spec:
  accessModes:
  - ReadWriteOnce
  storageClassName: ebs-sc
  resources:
    requests:
      storage: 4Gi
---
apiVersion: v1
kind: Pod
metadata:
  name: static-volume
spec:
  nodeSelector:
    topology.kubernetes.io/region: ap-south-1c
  containers:
  - name: nginx
    image: nginx
    volumeMounts:
    - name: static-volume
      mountPath: /data
  volumes:
  - name: static-volume
    persistentVolumeClaim:
      claimName: static-volume