apiVersion: apps/v1
kind: Deployment
metadata:
  name: mysql-deploymet
  namespace: expense
  labels:
    app: mysql
    tier: db
    project: expense
spec:
  replicas: 3
  selector:
    matchLabels:
      app: mysql
      tier: db
      project: expense
  template:
    metadata:
      labels:
        app: mysql
        tier: db
        project: expense
    spec:
      containers:
      - name: mysql
        image: chethankumar6/mysql
        ports:
        - containerPort: 3306
---
apiVersion: v1
kind: Service
metadata:
  name: mysql-service
  namespace: expense
spec:
  selector:
    app: mysql
    tier: db
    project: expense
  ports:
  - name: mysql-service
    protocol: TCP
    port: 3306
    targetPort: 3306

